"""Added server model

Revision ID: 33acf3bd3096
Revises: 15b935f85180
Create Date: 2024-06-05 05:05:47.617629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33acf3bd3096'
down_revision: Union[str, None] = '15b935f85180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('remind_delay', sa.Integer(), nullable=True),
    sa.Column('message_delete_delay', sa.Integer(), nullable=True),
    sa.Column('ping_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.add_column('events', sa.Column('server_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'events', 'servers', ['server_id'], ['server_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'server_id')
    op.drop_table('servers')
    # ### end Alembic commands ###
